// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBi4AHZKQ-fAFbDZVCSrNHZt-P5v5CwN4',
    appId: '1:787068453320:web:364155e352b2d2deef80fd',
    messagingSenderId: '787068453320',
    projectId: 'project-2251172459',
    authDomain: 'project-2251172459.firebaseapp.com',
    storageBucket: 'project-2251172459.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr1H98T_wHpdf3Dp70DY6g898BtWLOT3A',
    appId: '1:787068453320:android:ba13a3cd9cd710ffef80fd',
    messagingSenderId: '787068453320',
    projectId: 'project-2251172459',
    storageBucket: 'project-2251172459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_38dXdNYiahinwKe5J4sNhaDJyBs7Qf8',
    appId: '1:787068453320:ios:0c83d2b1b2d1f3c7ef80fd',
    messagingSenderId: '787068453320',
    projectId: 'project-2251172459',
    storageBucket: 'project-2251172459.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2251172459',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_38dXdNYiahinwKe5J4sNhaDJyBs7Qf8',
    appId: '1:787068453320:ios:0c83d2b1b2d1f3c7ef80fd',
    messagingSenderId: '787068453320',
    projectId: 'project-2251172459',
    storageBucket: 'project-2251172459.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2251172459',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBi4AHZKQ-fAFbDZVCSrNHZt-P5v5CwN4',
    appId: '1:787068453320:web:1af4baa2eb96d502ef80fd',
    messagingSenderId: '787068453320',
    projectId: 'project-2251172459',
    authDomain: 'project-2251172459.firebaseapp.com',
    storageBucket: 'project-2251172459.firebasestorage.app',
  );
}
